@extends('__ORBIT_LAYOUT__')
@section('__ORBIT_SECTION__')
<section class="orbit-page" data-orbit-view="moderation-report-show" data-report-id="{{ $reportId }}">
    <nav class="orbit-breadcrumbs" aria-label="Breadcrumb"><a href="{{ route('admin.console.operations.moderation.index') }}">Moderation &amp; Reports</a><span>/</span><strong>Report</strong></nav><a class="orbit-backlink" href="{{ route('admin.console.operations.moderation.index') }}">← Back to report queue</a>
    <div class="orbit-m4-skeleton" data-m4-loading aria-live="polite"><span></span><span></span><span></span></div><div class="orbit-state orbit-state--error" data-m4-error hidden><strong>Report could not be loaded.</strong><p data-m4-error-message></p><button class="orbit-button orbit-button--quiet" type="button" data-m4-retry>Try again</button></div>
    <div data-m4-content hidden><div class="orbit-page__heading orbit-page__heading--detail"><div><p class="orbit-eyebrow">Moderation case</p><h1 data-m4-title>Report</h1><p>Evidence is limited to what the reporter explicitly submitted; normal E2EE content is not decrypted for administrators.</p></div><div class="orbit-actionbar"><span data-m4-status></span><button class="orbit-button orbit-button--quiet" type="button" data-m4-action="assign">Assign</button><button class="orbit-button orbit-button--quiet" type="button" data-m4-action="workflow">Workflow</button><button class="orbit-button orbit-button--quiet" type="button" data-m4-action="note">Add note</button><button class="orbit-button orbit-button--danger" type="button" data-m4-action="enforce">Enforce</button></div></div>
    <div class="orbit-m4-detail-grid"><article class="orbit-panel orbit-m4-span-2"><div class="orbit-panel__header"><div><p class="orbit-eyebrow">Case</p><h2>Operational overview</h2></div><span class="orbit-m4-privacy-chip">Privacy-safe</span></div><dl class="orbit-kv-grid" data-m4-overview></dl></article><article class="orbit-panel orbit-m4-span-2"><div class="orbit-panel__header"><div><h2>Reporter-submitted evidence</h2><p>Explicit report evidence only. No universal plaintext access to encrypted messages or Moments.</p></div></div><div class="orbit-m4-evidence" data-m4-evidence></div></article><article class="orbit-panel"><div class="orbit-panel__header"><div><h2>Prior related reports</h2></div></div><div class="orbit-m4-timeline" data-m4-prior></div></article><article class="orbit-panel"><div class="orbit-panel__header"><div><h2>Risk context</h2></div></div><div data-m4-risk></div></article><article class="orbit-panel"><div class="orbit-panel__header"><div><h2>Private case notes</h2><p>Never consumer-visible.</p></div></div><div class="orbit-m4-timeline" data-m4-notes></div></article><article class="orbit-panel"><div class="orbit-panel__header"><div><h2>Decisions &amp; enforcement</h2></div></div><div class="orbit-m4-timeline" data-m4-enforcements></div></article></div></div>
</section>
@endsection
