<?php

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

beforeEach(function (): void {
    $this->withoutVite();
});

it('renders the SOS command center and incident detail inside the canonical console', function (): void {
    $index = $this->get('/admin/operations/sos')->assertOk();
    $detail = $this->get('/admin/operations/sos/01J-SAFE-INCIDENT')->assertOk();

    $index
        ->assertSee('data-orbit-canonical-shell="v1"', false)
        ->assertSee('data-orbit-view="sos-index"', false)
        ->assertSee('Safety / SOS')
        ->assertSee('Mission-critical')
        ->assertSee('server-side filters')
        ->assertDontSee('data-admin-auth-dialog', false);

    $detail
        ->assertSee('data-orbit-canonical-shell="v1"', false)
        ->assertSee('data-orbit-view="sos-show"', false)
        ->assertSee('Sensitive access')
        ->assertSee('reason-coded')
        ->assertDontSee('latitude', false)
        ->assertDontSee('longitude', false)
        ->assertDontSee('recording_ref', false)
        ->assertDontSee('ciphertext', false)
        ->assertDontSee('private_key', false);
});

it('registers canonical SOS web routes and a real sidebar destination', function (): void {
    $sidebar = file_get_contents(resource_path('views/admin/partials/sidebar.blade.php'));

    expect(Route::has('admin.console.operations.sos.index'))->toBeTrue()
        ->and(Route::has('admin.console.operations.sos.show'))->toBeTrue()
        ->and($sidebar)->toContain("route('admin.console.operations.sos.index')")
        ->and($sidebar)->toContain("routeIs('admin.console.operations.sos.*')")
        ->and($sidebar)->not->toContain('Safety / SOS</span><small>Next UI milestone');
});

it('keeps sensitive SOS data out of the blade source and requires explicit reveal workflows in JavaScript', function (): void {
    $index = file_get_contents(resource_path('views/admin/operations/sos/index.blade.php'));
    $detail = file_get_contents(resource_path('views/admin/operations/sos/show.blade.php'));
    $client = file_get_contents(resource_path('js/admin-console/sos.js'));
    $contract = file_get_contents(resource_path('js/admin-console/sos-contract.js'));

    expect($index)->not->toContain('latitude')
        ->and($index)->not->toContain('longitude')
        ->and($index)->not->toContain('recording_ref')
        ->and($detail)->not->toContain('latitude')
        ->and($detail)->not->toContain('longitude')
        ->and($detail)->not->toContain('recording_ref')
        ->and($client)->toContain('requestWithReauthentication')
        ->and($client)->toContain('applyActionPermissions')
        ->and($client)->toContain('readAdminSession')
        ->and($client)->toContain("adminApi('/api/admin/v1/auth/reauthenticate'")
        ->and($client)->toContain('clearSensitiveReveal')
        ->and($client)->toContain('sensitiveRevealTimer')
        ->and($contract)->toContain('Generated by setup/admin-ui-m3/generate-sos-contract.mjs')
        ->and($contract)->toContain('permissions:');
});
