@extends('__ORBIT_LAYOUT__')
@section('__ORBIT_SECTION__')
<section class="orbit-page" data-orbit-view="moderation-index">
    <nav class="orbit-breadcrumbs" aria-label="Breadcrumb"><strong>Moderation &amp; Reports</strong></nav>
    <div class="orbit-page__heading"><div><p class="orbit-eyebrow">Trust &amp; Safety</p><h1>Moderation &amp; Reports</h1><p>Unified, permission-aware report operations using reporter-submitted evidence and privacy-safe metadata.</p></div><button class="orbit-button orbit-button--quiet" type="button" data-m4-retry>Refresh</button></div>
    <nav class="orbit-m4-tabs" aria-label="Moderation sections"><a class="is-active" aria-current="page" href="{{ route('admin.console.operations.moderation.index') }}">Reports</a><a href="{{ route('admin.console.operations.moderation.appeals.index') }}">Appeals</a><a href="{{ route('admin.console.operations.moderation.risk.index') }}">Abuse &amp; Risk</a></nav>
    <form class="orbit-m4-filters" data-m4-report-filters><label>Search<input name="search" type="search" placeholder="Report, user, Circle or target"></label><label>Status<select name="status"><option value="">All</option><option>new</option><option>triaged</option><option>assigned</option><option>under_review</option><option>actioned</option><option>escalated</option><option>closed</option></select></label><label>Priority<select name="priority"><option value="">All</option><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>Assignment<select name="assignment"><option value="">All</option><option value="unassigned">Unassigned</option><option value="assigned">Assigned</option></select></label><button class="orbit-button" type="submit">Apply</button></form>
    <div class="orbit-m4-skeleton" data-m4-loading aria-live="polite"><span></span><span></span><span></span></div>
    <div class="orbit-state orbit-state--error" data-m4-error hidden><strong>Report queue could not be loaded.</strong><p data-m4-error-message></p><button class="orbit-button orbit-button--quiet" type="button" data-m4-retry>Try again</button></div>
    <div data-m4-content hidden><div class="orbit-m4-toolbar"><div><strong>Report queue</strong><p class="orbit-m4-muted">Server-filtered and paginated.</p></div><span class="orbit-m4-toolbar__meta" data-m4-count></span></div><div class="orbit-m4-table-wrap"><table class="orbit-m4-table"><thead><tr><th>Report</th><th>Target</th><th>Reason</th><th>Priority</th><th>Status</th><th>Assignee</th><th>Received</th></tr></thead><tbody data-m4-report-rows></tbody></table></div><div class="orbit-m4-empty" data-m4-empty hidden><strong>No reports match this view.</strong><p>Change filters or wait for new reports.</p></div><div class="orbit-m4-pagination" data-m4-pagination></div></div>
</section>
@endsection
