import {adminApi, listRows, pagination, unwrap} from './api-client.js';
import {askText,badge,debounce,errorText,escapeHtml,fmtDate,kv,maskIdentifier,setBusy,state,toast,valueOrDash} from './ui.js';

export function initUsersIndex(root) {
    const form=root.querySelector('[data-user-filters]'); const body=root.querySelector('[data-users-body]'); const base=root.dataset.detailBase; let page=1; let meta=null; let controller=null;
    const load=async()=>{ controller?.abort(); controller=new AbortController(); state(root,'loading'); const data=new FormData(form); const params=new URLSearchParams(); for(const [key,val] of data.entries()) if(String(val).trim()) params.set(key,String(val).trim()); params.set('page',String(page));
        try { const payload=await adminApi(`/api/admin/v1/users?${params}`,{signal:controller.signal}); const rows=listRows(payload); meta=pagination(payload,rows.length); if(!rows.length){state(root,'empty');return;} body.innerHTML=rows.map(user=>`<tr><td><div class="orbit-primary-cell"><strong>${escapeHtml(valueOrDash(user.name ?? user.display_name))}</strong><span>${escapeHtml(valueOrDash(user.email))}</span><small>${escapeHtml(user.id)}</small></div></td><td>${badge(user.status ?? user.account_status ?? 'active')}</td><td>${escapeHtml(valueOrDash(user.country ?? user.country_code))}</td><td>${badge(user.risk_classification ?? user.risk_level ?? 'normal')}</td><td>${escapeHtml(fmtDate(user.last_active_at ?? user.last_seen_at ?? user.updated_at))}</td><td><a class="orbit-row-open" href="${base}/${encodeURIComponent(user.id)}" aria-label="Open user">→</a></td></tr>`).join(''); root.querySelector('[data-page-summary]').textContent=`Page ${meta.current}${meta.last?` of ${meta.last}`:''} · ${meta.total} total`; root.querySelector('[data-prev]').disabled=!meta.hasPrev; root.querySelector('[data-next]').disabled=!meta.hasNext; state(root,'ready'); } catch(error){ if(error.name==='AbortError') return; state(root,'error',errorText(error)); }};
    const changed=debounce(()=>{page=1;load();}); form.addEventListener('input',changed); form.addEventListener('change',changed); root.querySelector('[data-prev]').addEventListener('click',()=>{if(meta?.hasPrev){page-=1;load();}}); root.querySelector('[data-next]').addEventListener('click',()=>{if(meta?.hasNext){page+=1;load();}}); root.querySelectorAll('[data-retry],[data-reload]').forEach(btn=>btn.addEventListener('click',load)); load();
}

function notesHtml(notes=[]) { return notes.length ? `<div class="orbit-note-list">${notes.map(n=>`<div><p>${escapeHtml(n.body ?? n.note ?? n.content ?? '')}</p><small>${escapeHtml(fmtDate(n.created_at))}</small></div>`).join('')}</div>` : '<p class="orbit-muted">No internal notes.</p>'; }
function tagsHtml(tags=[]) { return tags.length ? tags.map(t=>`<span class="orbit-tag">${escapeHtml(t.name ?? t.tag ?? t.label ?? t)}</span>`).join('') : '<span class="orbit-muted">No tags.</span>'; }

export function initUserShow(root) {
    const id=root.dataset.userId; let user={};
    async function load(){ root.querySelector('[data-loading]').hidden=false; root.querySelector('[data-error]').hidden=true; root.querySelector('[data-user-content]').hidden=true; try { const [detail,devices,sessions]=await Promise.all([adminApi(`/api/admin/v1/users/${encodeURIComponent(id)}`),adminApi(`/api/admin/v1/users/${encodeURIComponent(id)}/devices`),adminApi(`/api/admin/v1/users/${encodeURIComponent(id)}/sessions`)]); user=unwrap(detail); render(user,listRows(devices),listRows(sessions)); root.querySelector('[data-loading]').hidden=true; root.querySelector('[data-user-content]').hidden=false; } catch(error){root.querySelector('[data-loading]').hidden=true;root.querySelector('[data-error]').hidden=false;root.querySelector('[data-error-message]').textContent=errorText(error);} }
    function render(u,devices,sessions){ root.querySelector('[data-user-name]').textContent=u.name ?? u.display_name ?? `User ${id}`; root.querySelector('[data-user-id-label]').textContent=id; root.querySelector('[data-user-status]').innerHTML=badge(u.status ?? u.account_status ?? 'active'); root.querySelector('[data-user-overview]').innerHTML=kv([['Email',u.email],['Phone',u.phone_masked],['Country',u.country ?? u.country_code],['Created',fmtDate(u.created_at)],['Last activity',fmtDate(u.last_active_at ?? u.last_seen_at)],['Subscription',u.subscription?.plan_name ?? u.subscription?.plan_slug ?? u.plan],['Risk',u.risk_classification ?? u.risk_level],['Reverification',u.requires_reverification ?? u.reverification_required ? 'Required':'Not required']]); const controls=u.controls ?? u.operational_controls ?? {}; root.querySelector('[data-user-controls]').innerHTML=Object.keys(controls).length?Object.entries(controls).map(([k,v])=>`<div><span>${escapeHtml(k.replaceAll('_',' '))}</span><strong>${escapeHtml(typeof v==='object'?JSON.stringify(v):valueOrDash(v))}</strong></div>`).join(''):'<p class="orbit-muted">No active operational controls.</p>';
        root.querySelector('[data-devices]').innerHTML=devices.length?`<table><thead><tr><th>Device</th><th>Platform</th><th>Trust</th><th>Last seen</th><th></th></tr></thead><tbody>${devices.map(d=>`<tr><td><strong>${escapeHtml(valueOrDash(d.device_name ?? d.name))}</strong><small title="Masked device identifier">${escapeHtml(maskIdentifier(d.id ?? d.device_id))}</small></td><td>${escapeHtml(valueOrDash(d.platform))}</td><td>${badge(d.trust_status ?? d.status ?? 'unknown')}</td><td>${escapeHtml(fmtDate(d.last_seen_at))}</td><td><div class="orbit-row-actions"><button data-device-rotate="${escapeHtml(d.id ?? d.device_id)}" class="orbit-mini-button">Rotate token</button><button data-device-revoke="${escapeHtml(d.id ?? d.device_id)}" class="orbit-mini-button orbit-mini-button--danger">Revoke</button></div></td></tr>`).join('')}</tbody></table>`:'<p class="orbit-muted">No devices found.</p>';
        root.querySelector('[data-sessions]').innerHTML=sessions.length?`<table><thead><tr><th>Session</th><th>Device</th><th>Status</th><th>Last seen</th><th></th></tr></thead><tbody>${sessions.map(s=>`<tr><td><strong title="Masked session identifier">${escapeHtml(maskIdentifier(s.id ?? s.session_id))}</strong></td><td>${escapeHtml(valueOrDash(s.device_name ?? s.device_id))}</td><td>${badge(s.status ?? 'active')}</td><td>${escapeHtml(fmtDate(s.last_seen_at ?? s.updated_at))}</td><td><button data-session-revoke="${escapeHtml(s.id ?? s.session_id)}" class="orbit-mini-button orbit-mini-button--danger">Revoke</button></td></tr>`).join('')}</tbody></table>`:'<p class="orbit-muted">No active sessions.</p>'; root.querySelector('[data-notes]').innerHTML=notesHtml(u.notes ?? []); root.querySelector('[data-tags]').innerHTML=tagsHtml(u.tags ?? []); const status=String(u.status ?? u.account_status ?? '').toLowerCase(); root.querySelector('[data-action="suspend"]').hidden=status==='suspended'; root.querySelector('[data-action="activate"]').hidden=status!=='suspended'; bindRows(); }
    async function mutate(button,path,method,body,success){setBusy(button,true);try{await adminApi(path,{method,body});toast(success,'success');await load();}catch(e){toast(errorText(e),'error');}finally{setBusy(button,false);}}
    function bindRows(){root.querySelectorAll('[data-session-revoke]').forEach(btn=>btn.addEventListener('click',async()=>{const reason=await askText({title:'Revoke session',message:'This immediately invalidates the selected consumer session.',danger:true});if(reason)mutate(btn,`/api/admin/v1/users/${id}/sessions/${encodeURIComponent(btn.dataset.sessionRevoke)}`,'DELETE',{reason},'Session revoked.');})); root.querySelectorAll('[data-device-revoke]').forEach(btn=>btn.addEventListener('click',async()=>{const reason=await askText({title:'Revoke device',message:'This removes device trust/push routing and device-bound sessions.',danger:true});if(reason)mutate(btn,`/api/admin/v1/users/${id}/devices/${encodeURIComponent(btn.dataset.deviceRevoke)}`,'DELETE',{reason},'Device revoked.');})); root.querySelectorAll('[data-device-rotate]').forEach(btn=>btn.addEventListener('click',async()=>{const reason=await askText({title:'Force token rotation',message:'The device will need to rotate its consumer access token.'});if(reason)mutate(btn,`/api/admin/v1/users/${id}/devices/${encodeURIComponent(btn.dataset.deviceRotate)}/rotate-token`,'POST',{reason},'Token rotation required.');}));}
    root.querySelector('[data-retry]').addEventListener('click',load);
    root.querySelector('[data-action="logout-all"]').addEventListener('click',async(e)=>{const reason=await askText({title:'Force logout all sessions',message:'All consumer credentials for this user will be revoked.',danger:true});if(reason)mutate(e.currentTarget,`/api/admin/v1/users/${id}/sessions/revoke-all`,'POST',{reason},'All sessions revoked.');});
    root.querySelector('[data-action="suspend"]').addEventListener('click',async(e)=>{const reason=await askText({title:'Suspend user',message:'Suspension is a high-risk action and may require recent administrator reauthentication.',danger:true,confirm:'Suspend'});if(reason)mutate(e.currentTarget,`/api/admin/v1/users/${id}/status`,'PATCH',{status:'suspended',reason},'User suspended.');});
    root.querySelector('[data-action="activate"]').addEventListener('click',async(e)=>{const reason=await askText({title:'Reactivate user',message:'Restore consumer account access after reviewing the enforcement context.',confirm:'Reactivate'});if(reason)mutate(e.currentTarget,`/api/admin/v1/users/${id}/status`,'PATCH',{status:'active',reason},'User reactivated.');});
    root.querySelector('[data-action="add-note"]').addEventListener('click',async(e)=>{const value=await askText({title:'Add internal note',message:'Internal notes are not consumer-visible.',label:'Note',confirm:'Add note'});if(value)mutate(e.currentTarget,`/api/admin/v1/users/${id}/notes`,'POST',{body:value,note:value,content:value},'Internal note added.');});
    root.querySelector('[data-action="add-tag"]').addEventListener('click',async(e)=>{const value=await askText({title:'Add internal tag',message:'Use a concise operational tag.',label:'Tag',confirm:'Add tag'});if(value)mutate(e.currentTarget,`/api/admin/v1/users/${id}/tags`,'POST',{name:value,tag:value},'Tag added.');}); load();
}
